codeunit 51010 "WHA Labour Tests"
{
    Subtype = Test;
    TestPermissions = Disabled;

    var
        Assert: Codeunit "Library Assert";
        LocationTok: Label 'WHALAB', Locked = true;
        OtherLocationTok: Label 'WHALAB2', Locked = true;
        ItemTok: Label 'WHA-LAB-ITEM', Locked = true;
        OperatorTok: Label 'WHA-OPERATOR', Locked = true;

    [Test]
    procedure FinishedWorkBecomesRecordedTime()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourEntry: Record "WHA Labour Entry";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        TaskType: Enum "WHA Warehouse Task Type";
    begin
        // [SCENARIO] The task queue already records who did what and when. Nothing has ever read it, and
        // this is what reading it looks like.
        ConfigureLabour(0);
        CreateFinishedTask(WarehouseTask, 'LAB-TASK-1', TaskType::WHAPick, 10, 12);

        Assert.AreEqual(1, LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D), 'The finished job should have become one piece of recorded time.');

        FindEntryFor(LabourEntry, 'LAB-TASK-1');
        Assert.AreEqual(12, LabourEntry."Actual Minutes", 'The time should be the time between starting and finishing.');
        Assert.AreEqual(LabourEntry."Entry Type"::WHADirect, LabourEntry."Entry Type", 'Time on a job is direct time.');
        Assert.AreEqual(CopyStr(OperatorTok, 1, 50), LabourEntry."User ID", 'The time should belong to whoever held the job.');
    end;

    [Test]
    procedure TheSameJobIsNotCountedTwice()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        TaskType: Enum "WHA Warehouse Task Type";
    begin
        // [SCENARIO] Nothing tells labour management that a job finished, so the entries are generated by
        // asking. Asking twice must not double everybody's hours.
        ConfigureLabour(0);
        CreateFinishedTask(WarehouseTask, 'LAB-TASK-2', TaskType::WHAPick, 5, 8);

        LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D);

        Assert.AreEqual(0, LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D), 'A second run should take nothing.');
        Assert.AreEqual(1, EntryCountFor('LAB-TASK-2'), 'Only one piece of time should exist for the job.');
    end;

    [Test]
    procedure WorkNobodyHeldIsNotRecorded()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        TaskType: Enum "WHA Warehouse Task Type";
    begin
        // [SCENARIO] Time has to belong to somebody. A job completed with nobody holding it is a gap in the
        // record, not somebody's hour.
        ConfigureLabour(0);
        CreateFinishedTask(WarehouseTask, 'LAB-TASK-3', TaskType::WHAPick, 5, 8);
        WarehouseTask."Assigned To User ID" := '';
        WarehouseTask.Modify(true);

        Assert.AreEqual(0, LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D), 'Work nobody held should not become somebody time.');
    end;

    [Test]
    procedure TimeIsMeasuredAgainstTheStandardThatApplies()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourEntry: Record "WHA Labour Entry";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        TaskType: Enum "WHA Warehouse Task Type";
        Basis: Enum "WHA Labour Standard Basis";
    begin
        // [SCENARIO] A standard of two minutes a job and half a minute a unit makes ten units a seven
        // minute job. Doing it in fourteen is half the pace the standard expects.
        ConfigureLabour(0);
        CreateStandard('', TaskType::WHAPick, Basis::WHAFixedPlusUnit, 2, 0.5);
        CreateFinishedTask(WarehouseTask, 'LAB-TASK-4', TaskType::WHAPick, 10, 14);

        LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D);

        FindEntryFor(LabourEntry, 'LAB-TASK-4');
        Assert.IsTrue(LabourEntry."Measured Against Standard", 'A standard applied, so the time should be measured.');
        Assert.AreEqual(7, LabourEntry."Expected Minutes", 'Two minutes for the job and half a minute for each of ten units.');
        Assert.AreEqual(50, LabourEntry."Performance Percent", 'Seven expected against fourteen actual is half the expected pace.');
    end;

    [Test]
    procedure AStandardForTheLocationBeatsTheGeneralOne()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourEntry: Record "WHA Labour Entry";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        TaskType: Enum "WHA Warehouse Task Type";
        Basis: Enum "WHA Labour Standard Basis";
    begin
        // [SCENARIO] One site has longer aisles than another. A standard written for that site is the
        // whole reason the standard has a location on it.
        ConfigureLabour(0);
        CreateStandard('', TaskType::WHAPutAway, Basis::WHAFixedOnly, 5, 0);
        CreateStandard(CopyStr(LocationTok, 1, 10), TaskType::WHAPutAway, Basis::WHAFixedOnly, 20, 0);
        CreateFinishedTask(WarehouseTask, 'LAB-TASK-5', TaskType::WHAPutAway, 1, 20);

        LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D);

        FindEntryFor(LabourEntry, 'LAB-TASK-5');
        Assert.AreEqual(20, LabourEntry."Expected Minutes", 'The standard written for this location should win.');
    end;

    [Test]
    procedure TheFixedOnlyBasisIgnoresWhatWasHandled()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourEntry: Record "WHA Labour Entry";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        TaskType: Enum "WHA Warehouse Task Type";
        Basis: Enum "WHA Labour Standard Basis";
    begin
        // [SCENARIO] Moving one whole pallet takes as long whether it holds ten cases or a hundred, and a
        // warehouse that works that way should not have its people measured on the count.
        ConfigureLabour(0);
        CreateStandard('', TaskType::WHAMovement, Basis::WHAFixedOnly, 6, 99);
        CreateFinishedTask(WarehouseTask, 'LAB-TASK-6', TaskType::WHAMovement, 40, 6);

        LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D);

        FindEntryFor(LabourEntry, 'LAB-TASK-6');
        Assert.AreEqual(6, LabourEntry."Expected Minutes", 'The minutes per unit should have been ignored.');
        Assert.AreEqual(100, LabourEntry."Performance Percent", 'Six against six is exactly to standard.');
    end;

    [Test]
    procedure ABlockedStandardMeasuresNothing()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourStandard: Record "WHA Labour Standard";
        LabourEntry: Record "WHA Labour Entry";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        TaskType: Enum "WHA Warehouse Task Type";
        Basis: Enum "WHA Labour Standard Basis";
    begin
        // [SCENARIO] Blocking a standard is how a warehouse says it no longer believes the number. The
        // time is still recorded; it is just not scored against something nobody trusts.
        ConfigureLabour(0);
        CreateStandard('', TaskType::WHACount, Basis::WHAFixedPlusUnit, 3, 0.1);
        LabourStandard.Get('', TaskType::WHACount);
        LabourStandard.Validate(Blocked, true);
        LabourStandard.Modify(true);
        CreateFinishedTask(WarehouseTask, 'LAB-TASK-7', TaskType::WHACount, 10, 9);

        LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D);

        FindEntryFor(LabourEntry, 'LAB-TASK-7');
        Assert.AreEqual(9, LabourEntry."Actual Minutes", 'The time should still be recorded.');
        Assert.IsFalse(LabourEntry."Measured Against Standard", 'A blocked standard should measure nothing.');
        Assert.AreEqual(0, LabourEntry."Performance Percent", 'Unmeasured time has no performance.');
    end;

    [Test]
    procedure AJobTooLongToBelieveIsRecordedButNotMeasured()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourEntry: Record "WHA Labour Entry";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        TaskType: Enum "WHA Warehouse Task Type";
        Basis: Enum "WHA Labour Standard Basis";
    begin
        // [SCENARIO] Somebody started a job and went home. Counting that as eleven hours of work would ruin
        // every figure the warehouse looks at, and throwing it away would hide that it happened.
        ConfigureLabour(60);
        CreateStandard('', TaskType::WHAPick, Basis::WHAFixedPlusUnit, 2, 0.5);
        CreateFinishedTask(WarehouseTask, 'LAB-TASK-8', TaskType::WHAPick, 4, 700);

        LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D);

        FindEntryFor(LabourEntry, 'LAB-TASK-8');
        Assert.AreEqual(700, LabourEntry."Actual Minutes", 'The time should be recorded as it was.');
        Assert.IsFalse(LabourEntry."Measured Against Standard", 'Time that long should not be measured against a standard.');
    end;

    [Test]
    procedure TimeWithNoJobIsRecordedAsTimeOffTheJobs()
    var
        LabourEntry: Record "WHA Labour Entry";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        Reason: Enum "WHA Indirect Reason";
        EntryNo: Integer;
    begin
        // [SCENARIO] A warehouse where only the picking is measured looks more productive than it is. The
        // hours nobody counted are the ones worth finding.
        ConfigureLabour(0);

        EntryNo := LabourMgt.RecordIndirect(CopyStr(OperatorTok, 1, 50), CopyStr(LocationTok, 1, 10), WorkDate(), Reason::WHABreak, 15, 'Morning break');

        LabourEntry.Get(EntryNo);
        Assert.AreEqual(LabourEntry."Entry Type"::WHAIndirect, LabourEntry."Entry Type", 'Time off the jobs should be recorded as such.');
        Assert.AreEqual(15, LabourEntry."Actual Minutes", 'The time should be what was recorded.');
        Assert.IsFalse(LabourEntry."Measured Against Standard", 'There is no standard for a break.');
    end;

    [Test]
    procedure TimeOffTheJobsNeedsAPersonAndSomeMinutes()
    var
        LabourMgt: Codeunit "WHA Labour Mgt.";
        Reason: Enum "WHA Indirect Reason";
    begin
        // [SCENARIO] Time nobody spent, or time of no length, is not a record of anything.
        ConfigureLabour(0);

        asserterror LabourMgt.RecordIndirect('', CopyStr(LocationTok, 1, 10), WorkDate(), Reason::WHABreak, 15, '');
        Assert.ExpectedError('whose time');

        asserterror LabourMgt.RecordIndirect(CopyStr(OperatorTok, 1, 50), CopyStr(LocationTok, 1, 10), WorkDate(), Reason::WHABreak, 0, '');
        Assert.ExpectedError('how long it took');
    end;

    [Test]
    procedure AStandardOfNoTimeAtAllIsRefused()
    var
        LabourStandard: Record "WHA Labour Standard";
        TaskType: Enum "WHA Warehouse Task Type";
        Basis: Enum "WHA Labour Standard Basis";
    begin
        // [SCENARIO] A standard of zero would make every job that was ever done look infinitely slow.
        ConfigureLabour(0);
        CreateStandard('', TaskType::WHAPick, Basis::WHAFixedPlusUnit, 2, 0.5);
        LabourStandard.Get('', TaskType::WHAPick);
        LabourStandard.Validate("Minutes Per Unit", 0);

        asserterror LabourStandard.Validate("Minutes Per Job", 0);

        Assert.ExpectedError('has to allow some time');
    end;

    [Test]
    procedure ARunOnlyTakesWorkFromTheLocationItWasGiven()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourMgt: Codeunit "WHA Labour Mgt.";
        TaskType: Enum "WHA Warehouse Task Type";
    begin
        // [SCENARIO] Hours are reported per site, and a run for one site must not sweep in another.
        ConfigureLabour(0);
        CreateFinishedTask(WarehouseTask, 'LAB-TASK-9', TaskType::WHAPick, 5, 5);
        WarehouseTask."Location Code" := CopyStr(OtherLocationTok, 1, 10);
        WarehouseTask.Modify(true);

        Assert.AreEqual(0, LabourMgt.Generate(CopyStr(LocationTok, 1, 10), 0D, 0D), 'Work at another location should be left alone.');
    end;

    [Test]
    procedure DemoImportIsIdempotent()
    var
        LabourStandard: Record "WHA Labour Standard";
        DemoLabour: Codeunit "WHA Demo Labour";
        CountAfterFirstRun: Integer;
    begin
        // [SCENARIO] Importing the sample data twice creates the standards once.
        DemoLabour.Import();
        CountAfterFirstRun := LabourStandard.Count();

        DemoLabour.Import();

        Assert.AreEqual(CountAfterFirstRun, LabourStandard.Count(), 'A second import should not create more standards.');
    end;

    [Test]
    procedure TheScheduledGenerationTurnsFinishedWorkIntoTime()
    var
        LabourEntry: Record "WHA Labour Entry";
        WarehouseTask: Record "WHA Warehouse Task";
        TaskType: Enum "WHA Warehouse Task Type";
    begin
        // [SCENARIO] Segment 1 recorded that nothing schedules the generation. It was never missing logic,
        // only a runnable object for a job queue entry to point at.
        ConfigureLabour(0);
        EnableLabour();
        CreateFinishedTask(WarehouseTask, 'WHA-LB-S1', TaskType::WHAPick, 5, 30);

        LabourEntry.Reset();
        Codeunit.Run(Codeunit::"WHA Labour Scheduler", LabourEntry);

        LabourEntry.Reset();
        LabourEntry.SetRange("Task No.", 'WHA-LB-S1');
        Assert.IsFalse(LabourEntry.IsEmpty(), 'The scheduled run should have turned the finished job into measured time.');
    end;

    [Test]
    procedure TheScheduledGenerationRefusesWhenLabourIsSwitchedOff()
    var
        LabourEntry: Record "WHA Labour Entry";
    begin
        // [SCENARIO] A job queue entry left in place after somebody switched the feature off must not keep
        // working.
        ConfigureLabour(0);
        DisableLabour();
        LabourEntry.Reset();

        asserterror Codeunit.Run(Codeunit::"WHA Labour Scheduler", LabourEntry);

        Assert.ExpectedError('not enabled');
    end;

    [Test]
    procedure TheScheduledRunReadsOnlyTheWindowItWasGiven()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourEntry: Record "WHA Labour Entry";
        TaskType: Enum "WHA Warehouse Task Type";
        Basis: Enum "WHA Labour Standard Basis";
    begin
        // [SCENARIO] The run used to read every job the warehouse had ever finished, on every run, for
        // ever. It now reads the window in the setup — which means work older than the window is not
        // measured at all, and that is the trade the setting exists to let somebody make.
        ConfigureLabour(240);
        SetLookBackDays(7);
        EnableLabour();
        CreateStandard(CopyStr(LocationTok, 1, 10), TaskType::WHAPick, Basis::WHAFixedOnly, 5, 0);

        CreateFinishedTask(WarehouseTask, 'LAB-OLD-1', TaskType::WHAPick, 1, 5);
        WarehouseTask."Completed At" := CreateDateTime(WorkDate() - 60, 0T);
        WarehouseTask.Modify(false);

        CreateFinishedTask(WarehouseTask, 'LAB-NEW-1', TaskType::WHAPick, 1, 5);

        LabourEntry.Reset();
        Codeunit.Run(Codeunit::"WHA Labour Scheduler", LabourEntry);

        Assert.AreEqual(1, EntryCountFor('LAB-NEW-1'), 'Work inside the window should be measured.');
        Assert.AreEqual(0, EntryCountFor('LAB-OLD-1'), 'Work older than the window should be left alone.');
    end;

    [Test]
    procedure AWindowOfZeroStillReadsEverything()
    var
        WarehouseTask: Record "WHA Warehouse Task";
        LabourEntry: Record "WHA Labour Entry";
        TaskType: Enum "WHA Warehouse Task Type";
        Basis: Enum "WHA Labour Standard Basis";
    begin
        // [SCENARIO] Zero is the old behaviour, kept on purpose: a warehouse that would rather pay the
        // cost than risk missing anything can ask for every job ever finished.
        ConfigureLabour(240);
        SetLookBackDays(0);
        EnableLabour();
        CreateStandard(CopyStr(LocationTok, 1, 10), TaskType::WHAPick, Basis::WHAFixedOnly, 5, 0);

        CreateFinishedTask(WarehouseTask, 'LAB-OLD-2', TaskType::WHAPick, 1, 5);
        WarehouseTask."Completed At" := CreateDateTime(WorkDate() - 400, 0T);
        WarehouseTask.Modify(false);

        LabourEntry.Reset();
        Codeunit.Run(Codeunit::"WHA Labour Scheduler", LabourEntry);

        Assert.AreEqual(1, EntryCountFor('LAB-OLD-2'), 'A window of zero should still reach work from any date.');
    end;

    local procedure ConfigureLabour(MaxJobMinutes: Decimal)
    var
        Setup: Record "WHA Labour Setup";
        TaskSetup: Record "WHA Warehouse Task Setup";
    begin
        Setup.Reset();
        if not Setup.Get() then begin
            Setup.Init();
            Setup.Insert(true);
        end;
        Setup.Validate("Max Job Minutes", MaxJobMinutes);
        Setup.Modify(true);

        TaskSetup.Reset();
        if not TaskSetup.Get() then begin
            TaskSetup.Init();
            TaskSetup.Insert(true);
        end;
        TaskSetup.Validate("Auto Release Tasks", false);
        TaskSetup.Modify(true);

        EnsureLocation(CopyStr(LocationTok, 1, 10));
        EnsureLocation(CopyStr(OtherLocationTok, 1, 10));
    end;

    local procedure CreateStandard(LocationCode: Code[10]; TaskType: Enum "WHA Warehouse Task Type"; Basis: Enum "WHA Labour Standard Basis"; MinutesPerJob: Decimal; MinutesPerUnit: Decimal)
    var
        LabourStandard: Record "WHA Labour Standard";
    begin
        if LabourStandard.Get(LocationCode, TaskType) then
            exit;

        LabourStandard.Init();
        LabourStandard."Location Code" := LocationCode;
        LabourStandard."Task Type" := TaskType;
        LabourStandard.Validate(Basis, Basis);
        LabourStandard.Validate("Minutes Per Job", MinutesPerJob);
        LabourStandard.Validate("Minutes Per Unit", MinutesPerUnit);
        LabourStandard.Insert(true);
    end;

    local procedure CreateFinishedTask(var WarehouseTask: Record "WHA Warehouse Task"; TaskNo: Code[20]; TaskType: Enum "WHA Warehouse Task Type"; Quantity: Decimal; MinutesTaken: Integer)
    var
        TookThisLong: Duration;
    begin
        TookThisLong := MinutesTaken * 60000;

        WarehouseTask.Init();
        WarehouseTask."No." := TaskNo;
        WarehouseTask."Task Type" := TaskType;
        WarehouseTask."Location Code" := CopyStr(LocationTok, 1, 10);
        WarehouseTask."Item No." := CopyStr(ItemTok, 1, 20);
        WarehouseTask.Quantity := Quantity;
        WarehouseTask."Quantity Handled" := Quantity;
        WarehouseTask.Status := WarehouseTask.Status::WHACompleted;
        WarehouseTask."Assigned To User ID" := CopyStr(OperatorTok, 1, 50);
        WarehouseTask."Started At" := CurrentDateTime;
        WarehouseTask."Completed At" := WarehouseTask."Started At" + TookThisLong;
        WarehouseTask.Insert(true);
    end;

    local procedure FindEntryFor(var LabourEntry: Record "WHA Labour Entry"; TaskNo: Code[20])
    begin
        LabourEntry.Reset();
        LabourEntry.SetRange("Task No.", TaskNo);
        LabourEntry.FindFirst();
    end;

    local procedure EntryCountFor(TaskNo: Code[20]): Integer
    var
        LabourEntry: Record "WHA Labour Entry";
    begin
        LabourEntry.SetRange("Task No.", TaskNo);
        exit(LabourEntry.Count());
    end;

    local procedure EnsureLocation(LocationCode: Code[10])
    var
        Location: Record Location;
    begin
        if Location.Get(LocationCode) then
            exit;

        Location.Init();
        Location.Code := LocationCode;
        Location.Insert();
    end;

    local procedure EnableLabour()
    begin
        SetLabourEnabled(true);
    end;

    local procedure DisableLabour()
    begin
        SetLabourEnabled(false);
    end;

    local procedure SetLabourEnabled(Enabled: Boolean)
    var
        Setup: Record "WHA Labour Setup";
    begin
        Setup.Get();
        Setup."WHA Enabled" := Enabled;
        Setup.Modify(true);
    end;

    local procedure SetLookBackDays(Days: Integer)
    var
        Setup: Record "WHA Labour Setup";
    begin
        Setup.Get();
        Setup.Validate("Look Back Days", Days);
        Setup.Modify(true);
    end;

}
