namespace WarehouseAdvanced.Core;

using WarehouseAdvanced.DirectedWork;
using WarehouseAdvanced.HandlingUnit;
using WarehouseAdvanced.Integration;
using WarehouseAdvanced.MobileDevice;
using WarehouseAdvanced.WaveManagement;

permissionset 50000 "WHA Objects"
{
    Assignable = false;
    Caption = 'Warehouse Advanced - Objects', Locked = true;

    Permissions =
        table "WHA Warehouse Setup" = X,
        table "WHA Setup Step" = X,
        page "WHA Warehouse Setup" = X,
        page "WHA Setup Hub" = X,
        page "WHA Feature Setup Wizard" = X,
        page "WHA API Warehouse Setup" = X,
        codeunit "WHA Warehouse Setup Logic" = X,
        codeunit "WHA Default Feature Setup" = X,
        codeunit "WHA Feature Mgt." = X,
        codeunit "WHA Guided Setup" = X,
        codeunit "WHA Install" = X,
        codeunit "WHA Upgrade" = X,
        codeunit "WHA MCP Setup" = X,
        table "WHA Handling Unit Setup" = X,
        table "WHA Handling Unit" = X,
        table "WHA Handling Unit Line" = X,
        page "WHA Handling Unit Setup" = X,
        page "WHA Handling Unit Card" = X,
        page "WHA Handling Units" = X,
        page "WHA API Handling Unit" = X,
        page "WHA Handling Unit Lines" = X,
        page "WHA API Handling Unit Line" = X,
        codeunit "WHA Handling Unit Logic" = X,
        codeunit "WHA HU Line Logic" = X,
        codeunit "WHA HU Feature Setup" = X,
        codeunit "WHA HU App Area Sub." = X,
        table "WHA Demo Data" = X,
        codeunit "WHA Demo Handling Unit" = X,
        page "WHA API Demo Handling Unit" = X,
        table "WHA Warehouse Task Setup" = X,
        table "WHA Warehouse Task" = X,
        page "WHA Warehouse Task Setup" = X,
        page "WHA Warehouse Task Card" = X,
        page "WHA Warehouse Tasks" = X,
        page "WHA API Warehouse Task" = X,
        codeunit "WHA Warehouse Task Logic" = X,
        codeunit "WHA Task Feature Setup" = X,
        codeunit "WHA Task App Area Sub." = X,
        codeunit "WHA Demo Warehouse Task" = X,
        page "WHA API Demo Warehouse Task" = X,
        table "WHA Integration Setup" = X,
        table "WHA Integration Message" = X,
        page "WHA Integration Setup" = X,
        page "WHA Integration Messages" = X,
        page "WHA Integration Message Card" = X,
        page "WHA API Integration Message" = X,
        codeunit "WHA Integration Msg. Logic" = X,
        codeunit "WHA Int. Message Mgt." = X,
        codeunit "WHA Int. Message Runner" = X,
        codeunit "WHA Int. Unhandled Message" = X,
        codeunit "WHA Int. Task Request" = X,
        codeunit "WHA Int. Task Confirm" = X,
        codeunit "WHA Int. HU Received" = X,
        codeunit "WHA Int. HU Shipped" = X,
        codeunit "WHA Int. Feature Setup" = X,
        codeunit "WHA Int. App Area Sub." = X,
        codeunit "WHA Demo Integration" = X,
        page "WHA API Demo Integration" = X,
        table "WHA RF Setup" = X,
        table "WHA RF Device" = X,
        page "WHA RF Setup" = X,
        page "WHA RF Devices" = X,
        page "WHA RF Device Card" = X,
        page "WHA RF Handheld" = X,
        page "WHA API RF Device" = X,
        codeunit "WHA RF Standard Flow" = X,
        codeunit "WHA RF Feature Setup" = X,
        codeunit "WHA RF App Area Sub." = X,
        codeunit "WHA Demo RF Device" = X,
        page "WHA API Demo RF Device" = X,
        table "WHA Wave Setup" = X,
        table "WHA Wave" = X,
        page "WHA Wave Setup" = X,
        page "WHA Waves" = X,
        page "WHA Wave Card" = X,
        page "WHA API Wave" = X,
        codeunit "WHA Wave Logic" = X,
        codeunit "WHA Wave Default Strategy" = X,
        codeunit "WHA Wave Due Strategy" = X,
        codeunit "WHA Wave Strategy Filters" = X,
        codeunit "WHA Wave Feature Setup" = X,
        codeunit "WHA Wave App Area Sub." = X,
        codeunit "WHA Demo Wave" = X,
        page "WHA API Demo Wave" = X;
}
