namespace WarehouseAdvanced.LabourManagement;

using WarehouseAdvanced.DirectedWork;

codeunit 50352 "WHA Labour Mgt."
{
    Access = Public;

    var
        NoMinutesErr: Label 'Record how long it took. Time of no length is not time spent.';
        NoPersonErr: Label 'Say whose time this is.';

    /// <summary>
    /// Turns finished warehouse work into recorded time. Nothing in directed work tells labour management
    /// that a job finished — the same rule the rest of the app follows — so the entries are generated by
    /// asking, and a job that already has an entry is never counted twice.
    /// </summary>
    /// <param name="LocationCode">The location to look at. Blank looks everywhere.</param>
    /// <param name="FromDate">The first day to take work from. Blank reads back to the beginning.</param>
    /// <param name="ToDate">The last day to take work from. Blank reads up to the present.</param>
    /// <returns>How many entries were created.</returns>
    /// <remarks>
    /// The dates are put on the record before it is read, not checked after, so a bounded run asks the
    /// database for a week of work rather than for every job the warehouse has ever finished. The check
    /// afterwards stays: it is what excludes a job marked complete with no time on it, which no date
    /// filter can express.
    /// </remarks>
    procedure Generate(LocationCode: Code[10]; FromDate: Date; ToDate: Date): Integer
    var
        WarehouseTask: Record "WHA Warehouse Task";
        Created: Integer;
    begin
        WarehouseTask.SetCurrentKey(Status, "Location Code");
        WarehouseTask.SetRange(Status, WarehouseTask.Status::WHACompleted);
        if LocationCode <> '' then
            WarehouseTask.SetRange("Location Code", LocationCode);
        ApplyDateFilter(WarehouseTask, FromDate, ToDate);
        if not WarehouseTask.FindSet() then
            exit(0);

        repeat
            if IsInRange(WarehouseTask, FromDate, ToDate) then
                if CreateEntryFor(WarehouseTask) <> 0 then
                    Created += 1;
        until WarehouseTask.Next() = 0;

        exit(Created);
    end;

    /// <summary>
    /// Records time that was not spent on a warehouse job. A warehouse where only the picking is measured
    /// looks more productive than it is, and the hours nobody counted are exactly the ones worth finding.
    /// </summary>
    /// <param name="ForUserId">Whose time it is.</param>
    /// <param name="LocationCode">Where it was spent.</param>
    /// <param name="PostingDate">The day it belongs to.</param>
    /// <param name="Reason">What it was spent on.</param>
    /// <param name="Minutes">How long it took.</param>
    /// <param name="EntryDescription">What it was, in the words of whoever recorded it.</param>
    /// <returns>The entry number of the time recorded.</returns>
    procedure RecordIndirect(ForUserId: Code[50]; LocationCode: Code[10]; PostingDate: Date; Reason: Enum "WHA Indirect Reason"; Minutes: Decimal; EntryDescription: Text[100]): Integer
    var
        LabourEntry: Record "WHA Labour Entry";
    begin
        if ForUserId = '' then
            Error(NoPersonErr);
        if Minutes <= 0 then
            Error(NoMinutesErr);

        LabourEntry.Init();
        LabourEntry."Entry Type" := LabourEntry."Entry Type"::WHAIndirect;
        LabourEntry.Validate("User ID", ForUserId);
        LabourEntry.Validate("Location Code", LocationCode);
        LabourEntry.Validate("Posting Date", PostingDate);
        LabourEntry.Validate("Indirect Reason", Reason);
        LabourEntry.Validate(Description, EntryDescription);
        LabourEntry.Validate("Actual Minutes", Minutes);
        LabourEntry.Insert(true);

        exit(LabourEntry."Entry No.");
    end;

    /// <summary>
    /// Answers how long a piece of work should have taken, using the standard that applies to it.
    /// </summary>
    /// <param name="TaskType">The kind of work.</param>
    /// <param name="LocationCode">Where it happened.</param>
    /// <param name="QuantityHandled">How much was moved.</param>
    /// <param name="Measured">Receives whether a standard applied at all.</param>
    /// <returns>The expected time in minutes, or zero where nothing measured it.</returns>
    procedure ExpectedMinutes(TaskType: Enum "WHA Warehouse Task Type"; LocationCode: Code[10]; QuantityHandled: Decimal; var Measured: Boolean): Decimal
    var
        LabourStandard: Record "WHA Labour Standard";
        Basis: Interface "WHA ILabourStandard";
    begin
        Measured := false;
        if not FindStandard(LabourStandard, TaskType, LocationCode) then
            exit(0);

        Measured := true;
        Basis := LabourStandard.Basis;
        exit(Round(Basis.ExpectedMinutes(LabourStandard, QuantityHandled), 0.01));
    end;

    /// <summary>
    /// Finds the standard that applies to a kind of work at a location: the one written for that location
    /// if there is one, otherwise the one written for everywhere.
    /// </summary>
    /// <param name="LabourStandard">Receives the standard that applies.</param>
    /// <param name="TaskType">The kind of work.</param>
    /// <param name="LocationCode">Where it happened.</param>
    /// <returns>True when a standard applies and is not blocked.</returns>
    procedure FindStandard(var LabourStandard: Record "WHA Labour Standard"; TaskType: Enum "WHA Warehouse Task Type"; LocationCode: Code[10]): Boolean
    begin
        if LocationCode <> '' then
            if LabourStandard.Get(LocationCode, TaskType) then
                exit(not LabourStandard.Blocked);

        if not LabourStandard.Get('', TaskType) then
            exit(false);
        exit(not LabourStandard.Blocked);
    end;

    /// <summary>
    /// Describes in one line how a standard works out expected time.
    /// </summary>
    /// <param name="LabourStandard">The standard to describe.</param>
    /// <returns>A short description in the user's language.</returns>
    procedure DescribeBasis(var LabourStandard: Record "WHA Labour Standard"): Text
    var
        Basis: Interface "WHA ILabourStandard";
    begin
        Basis := LabourStandard.Basis;
        exit(Basis.Describe());
    end;

    local procedure CreateEntryFor(var WarehouseTask: Record "WHA Warehouse Task"): Integer
    var
        LabourEntry: Record "WHA Labour Entry";
        EntryLogic: Codeunit "WHA Labour Entry Logic";
        ActualMinutes: Decimal;
        ExpectedMinutesValue: Decimal;
        Measured: Boolean;
    begin
        if WarehouseTask."Assigned To User ID" = '' then
            exit(0);
        if HasEntry(WarehouseTask."No.") then
            exit(0);

        ActualMinutes := EntryLogic.MinutesBetween(WarehouseTask."Started At", WarehouseTask."Completed At");
        if ActualMinutes <= 0 then
            exit(0);

        ExpectedMinutesValue := ExpectedMinutes(WarehouseTask."Task Type", WarehouseTask."Location Code", QuantityOf(WarehouseTask), Measured);
        if Measured and IsTooLongToBelieve(ActualMinutes) then
            Measured := false;

        LabourEntry.Init();
        LabourEntry."Entry Type" := LabourEntry."Entry Type"::WHADirect;
        LabourEntry."User ID" := WarehouseTask."Assigned To User ID";
        LabourEntry."Location Code" := WarehouseTask."Location Code";
        LabourEntry."Task No." := WarehouseTask."No.";
        LabourEntry."Task Type" := WarehouseTask."Task Type";
        LabourEntry."Quantity Handled" := QuantityOf(WarehouseTask);
        LabourEntry.Description := WarehouseTask.Description;
        LabourEntry."Started At" := WarehouseTask."Started At";
        LabourEntry."Ended At" := WarehouseTask."Completed At";
        LabourEntry."Actual Minutes" := ActualMinutes;
        LabourEntry."Measured Against Standard" := Measured;
        if Measured then
            LabourEntry."Expected Minutes" := ExpectedMinutesValue;
        LabourEntry.Insert(true);

        LabourEntry."Performance Percent" := EntryLogic.PerformanceOf(LabourEntry);
        LabourEntry.Modify(true);

        exit(LabourEntry."Entry No.");
    end;

    local procedure HasEntry(TaskNo: Code[20]): Boolean
    var
        LabourEntry: Record "WHA Labour Entry";
    begin
        LabourEntry.SetCurrentKey("Task No.");
        LabourEntry.SetRange("Task No.", TaskNo);
        exit(not LabourEntry.IsEmpty());
    end;

    local procedure ApplyDateFilter(var WarehouseTask: Record "WHA Warehouse Task"; FromDate: Date; ToDate: Date)
    var
        OneMillisecond: Duration;
    begin
        OneMillisecond := 1;

        if (FromDate <> 0D) and (ToDate <> 0D) then begin
            WarehouseTask.SetRange("Completed At", CreateDateTime(FromDate, 0T), CreateDateTime(ToDate + 1, 0T) - OneMillisecond);
            exit;
        end;

        if FromDate <> 0D then begin
            WarehouseTask.SetFilter("Completed At", '>=%1', CreateDateTime(FromDate, 0T));
            exit;
        end;

        if ToDate <> 0D then
            WarehouseTask.SetFilter("Completed At", '<=%1', CreateDateTime(ToDate + 1, 0T) - OneMillisecond);
    end;

    local procedure IsInRange(var WarehouseTask: Record "WHA Warehouse Task"; FromDate: Date; ToDate: Date): Boolean
    var
        CompletedOn: Date;
    begin
        if WarehouseTask."Completed At" = 0DT then
            exit(false);

        CompletedOn := DT2Date(WarehouseTask."Completed At");
        if (FromDate <> 0D) and (CompletedOn < FromDate) then
            exit(false);
        if (ToDate <> 0D) and (CompletedOn > ToDate) then
            exit(false);
        exit(true);
    end;

    local procedure QuantityOf(var WarehouseTask: Record "WHA Warehouse Task"): Decimal
    begin
        if WarehouseTask."Quantity Handled" > 0 then
            exit(WarehouseTask."Quantity Handled");
        exit(WarehouseTask.Quantity);
    end;

    local procedure IsTooLongToBelieve(ActualMinutes: Decimal): Boolean
    var
        Setup: Record "WHA Labour Setup";
    begin
        Setup.SetLoadFields("Max Job Minutes");
        if not Setup.Get() then
            exit(false);
        if Setup."Max Job Minutes" <= 0 then
            exit(false);

        exit(ActualMinutes > Setup."Max Job Minutes");
    end;
}
